[versions]
junit-platform = "1.14.2"
oci-registry = "0.7.0"
slf4j = "2.0.17"
testcontainers = "2.0.3"

[libraries]
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit-platform" }
oci-registry = { module = "io.github.sgtsilvio:oci-registry", version.ref = "oci-registry" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
testcontainers = { module = "org.testcontainers:testcontainers", version.ref = "testcontainers" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version = "2.2.21" }
defaults = { id = "io.github.sgtsilvio.gradle.defaults", version = "0.2.0" }
mavenCentralPublishing = { id = "io.github.sgtsilvio.gradle.maven-central-publishing", version = "0.4.1" }
metadata = { id = "io.github.sgtsilvio.gradle.metadata", version = "0.6.0" }
